/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CmsContentIndexRouteImport } from './routes/cms/content/index'
import { Route as CmsContentNewRouteImport } from './routes/cms/content/new'
import { Route as CmsContentContentIdIndexRouteImport } from './routes/cms/content/$contentId/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsContentIndexRoute = CmsContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => CmsRoute,
} as any)
const CmsContentNewRoute = CmsContentNewRouteImport.update({
  id: '/content/new',
  path: '/content/new',
  getParentRoute: () => CmsRoute,
} as any)
const CmsContentContentIdIndexRoute =
  CmsContentContentIdIndexRouteImport.update({
    id: '/content/$contentId/',
    path: '/content/$contentId/',
    getParentRoute: () => CmsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cms': typeof CmsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/cms/content/new': typeof CmsContentNewRoute
  '/cms/content': typeof CmsContentIndexRoute
  '/cms/content/$contentId': typeof CmsContentContentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cms': typeof CmsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/cms/content/new': typeof CmsContentNewRoute
  '/cms/content': typeof CmsContentIndexRoute
  '/cms/content/$contentId': typeof CmsContentContentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cms': typeof CmsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/cms/content/new': typeof CmsContentNewRoute
  '/cms/content/': typeof CmsContentIndexRoute
  '/cms/content/$contentId/': typeof CmsContentContentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cms'
    | '/dashboard'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/cms/content/new'
    | '/cms/content'
    | '/cms/content/$contentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cms'
    | '/dashboard'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/cms/content/new'
    | '/cms/content'
    | '/cms/content/$contentId'
  id:
    | '__root__'
    | '/'
    | '/cms'
    | '/dashboard'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/cms/content/new'
    | '/cms/content/'
    | '/cms/content/$contentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CmsRoute: typeof CmsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/content/': {
      id: '/cms/content/'
      path: '/content'
      fullPath: '/cms/content'
      preLoaderRoute: typeof CmsContentIndexRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/content/new': {
      id: '/cms/content/new'
      path: '/content/new'
      fullPath: '/cms/content/new'
      preLoaderRoute: typeof CmsContentNewRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/content/$contentId/': {
      id: '/cms/content/$contentId/'
      path: '/content/$contentId'
      fullPath: '/cms/content/$contentId'
      preLoaderRoute: typeof CmsContentContentIdIndexRouteImport
      parentRoute: typeof CmsRoute
    }
  }
}

interface CmsRouteChildren {
  CmsContentNewRoute: typeof CmsContentNewRoute
  CmsContentIndexRoute: typeof CmsContentIndexRoute
  CmsContentContentIdIndexRoute: typeof CmsContentContentIdIndexRoute
}

const CmsRouteChildren: CmsRouteChildren = {
  CmsContentNewRoute: CmsContentNewRoute,
  CmsContentIndexRoute: CmsContentIndexRoute,
  CmsContentContentIdIndexRoute: CmsContentContentIdIndexRoute,
}

const CmsRouteWithChildren = CmsRoute._addFileChildren(CmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CmsRoute: CmsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
